modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/wolfieboy09/Mekanism-x-Northstar/issues"

[[mods]]
modId="mek_x_star"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/wolfieboy09/Mekanism-x-Northstar/refs/heads/master/updates.json"
displayURL="https://github.com/wolfieboy09/Mekanism-x-Northstar"
logoFile="mek_x_star_logo.png"

authors="Wolfieboy09"

description='''${mod_description}'''

[[mixins]]
config="mek_x_star.mixins.json"

[[dependencies.mek_x_star]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mek_x_star]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
